### ISSUE TITLE
`_proposalID` wrap around

### ISSUE THREAD

**Issue by colm** [slockit/DAO#108]
Can we call `newProposal` so many times that `_proposalID` wraps around. Then we can call `newProposal` and change the creator of proposals with high deposits. Then we can call `executeProposal` and get the proposal deposit sent to us.

**Comment by LefterisJP** [comment]
So you suggest wrapping around `_proposalID` in order to be able to edit already existing and open proposals?

I think this is impossible. Each `newProposal()` attempt costs you gas and a proposal deposit (if it exists). For a `uint256` to wrap around you would need to call `newProposal()` A LOT OF times. To give you a comparison, [according to Wolfram Alpha](https://www.wolframalpha.com/input/?i=how+big+is+2^256-1) you would need to call `newProposal()` as many times as is 0.0012 of the atoms existing in the visible universe. Now multiply that by the gas each proposal would cost and you are more than broke ;)

**Comment by colm** [comment]
Yes. 

I think its 1.1579209e+77 which is gonna cost ALOT. with gas + deposit.

**Comment by CJentzsch** [comment]
You need to call it `2^256` times. With a mximum of about 10tx/s , this will take a very very long time...
