### ISSUE TITLE
Should `curator` be in allowed recipients

### ISSUE THREAD

**Issue by colm** [slockit/DAO#109]
Is there a need to add `curator` to [`allowedRecipients`](https://github.com/slockit/DAO/blob/master/DAO.sol#L379)

**Comment by CJentzsch** [comment]
No, it doesn't need to, but I did for 2 reasons:

1. He can put himself there anyway. So not putting him there doesn't change much
2. In the case of a split, where someone just wants to get his ether back. We save him one step while doing this, because he doesn't need to set his address to the whitelist in his new DAO before retrieving the ether. He can be the new curator and send the ether to himself.
