### ISSUE TITLE
Quorum rules defeated by multiple proposals. 

### ISSUE THREAD

**Issue by colm** [slockit/DAO#110]
I am a little worried instead of making 1 proposal to spend all the ETH of the DAO. Someone can make 20. In the case where the `this.balance = 100 ETH` the quorum will be 20% on 20 proposals to spend 5 ETH and can be passed by a minority to spend all the ETH. 

Defeating the quorum rules that more users need to agree in order to pass a proposal that spends more ETH.

**Comment by CJentzsch** [comment]
In order to do this, he would first need to be on the whitelist. Let's say he had once planned to have a valid propsal, and is no vandalizing with this proposal spam. The curator would immediately take him from the whitelist, so that his proposals can't be executed: https://github.com/slockit/DAO/blob/master/DAO.sol#L533-L537

The Curator is there to protect the DAO in such scenarios.
