### ISSUE TITLE
adding test scenarios

### ISSUE THREAD

**Issue by dazzaji** [slockit/DAO#145]
US legal hackers/researchers new to this code base looking to add more test scenarios (here: https://github.com/slockit/DAO/tree/master/tests).  Clues/cautions/ideas/help are welcome. 

Context: This DAO code seem to fit a law.mit.edu autonomous Credit Union prototype.  The prototype would test a few things, including how well Solidity can meet a few common regulatory compliance requirements. We are looking at some data provided by Solidity (and maybe better with this DAO design) that regulators/auditors can use to objectively, verifiably test legal compliance with requirements not covered by the current test scenarios.  Seems the best next step is to create them and test it out, right?

I invite anybody familiar with this DAO project to come hack the law (in a good way!) with us on a prototypejam hangout or skype sesh. HT to @ peterchau (in DOAhub slack) who suggested I inquire with this issue.

**Comment by MesserArtStudio** [comment]
When you'll need some continental EU regulations hints I can probably suggest some. Common Law isn't in my scope of expertise. However as I dig into this subject quite often and AML regulations worldwide were in my scope of interest due to professional reasons I would suggest looking into US Treasury vs Thomas Haider which could apply to DAO as well.

**Comment by desdonnelly** [comment]
I'm just curious why this would be necessary since how will any Govt entity anywhere serve papers/notices on the thousands of address keys of participants, or failing that how they would then propose to 'censor' the Ethereum network? to quote Buckminster Fuller:-

“You never change things by fighting the existing reality.
To change something, build a new model that makes the existing model obsolete.”

**Comment by MesserArtStudio** [comment]
Hi Des. As to "build a new model" - assume that some qualities behind DAO are not in line with politics (and aren't as "tyrranization" of western democracies is slowly proceeding). Certain individuals in charge of calming such ideas could just make a DAO (or join existing one) and then initiate something that can be categorized as preparation for terrorist act. That's all. Panic, media, laws passed without even reading them. People are eager to give up their liberties when properly scared :) . Does it sound like a "new model"?

**Comment by lzys** [comment]
Can help with securities regulations, corporate governance and international law.

**Comment by CJentzsch** [comment]
I will close this, since this is a more general issue, not directly related to the codebase. If you think otherwise, please reopen.

**Comment by dazzaji** [comment]
Yes, it's totally fine to close this issue now.  We're about to contact people who indicated interest in the project.  Thanks.
