### ISSUE TITLE
Blocked addresses should have a blocked token count

### ISSUE THREAD

**Issue by tuxbear** [slockit/DAO#208]
Use case: 
I have voted with my "The DAO" account (A1) I buy more tokens, transfer them to A1. Now they are locked, and they shouldn't be. The locking mechanism seems too primitive:

`    mapping (address => uint) public blocked;`

I can see in the source code that the blocking map discriminates on the account level. It would be ideal to map the addresses to a count (blockedNumberOfTokens)

The same approach should be used for proposals. If I vote from A1 for P5 with 1000 tokens, and then acquire more tokens (let's say 500) into A1, I should be able to vote again for P5, and the DAO contract should increase the votes on P5 and the lockedNumberOfTokens to 1500 for A1.

I haven't had the time to look too much at the code and I'm quite new to the EVM, so I have to make a disclaimer that I don't know if this feature is technically viable.

**Comment by LefterisJP** [comment]
Yes once you transfer tokens to an account that is already blocked those new tokens also become blocked.

This is just how the system is designed. It would be overly complicated to count number of tokens blocked instead of accounts blocked and add unneeded complexity to the contract.

You can always use multiple accounts to vote on different proposals if you buy new tokens.

**Comment by CJentzsch** [comment]
This is something to be dealt with in the UI, not at the operatin system level (the DAO contract) :-)
