### ISSUE TITLE
May not be executing proposals in certain situations

### ISSUE THREAD

**Issue by cougarously** [slockit/DAO#214]
I'm new to Solidity and just took first pass of all the DAO code, so I'm not 100% sure but I think this may be a bug.

Let's say that we have halved the minimum quorum by doubling the minQuorumDivisor (=10) because it took a long time for a quorum to be met. So looking at the code below which is part of the DAO.executeProposal() function , the  first 'if' statement checks that we've met the lower halved quorum requirement. We enter that first 'if' statement and it modifies the minQuorumDivisor back to higher 20% requirement (minQuorumDivisor=5). Then immediately after we attempt to execute the proposal where there's a second 'if' statement checking to see ii the quorum is met again but now it has the higher quorum requirement since DAO.minQuorum() is a function of the minQuorumDivisor that was just previously reset to 20%. So, isn't it possible that the in some situations that proposal never gets executed?

```
if (quorum >= minQuorum(p.amount)) {
   ...
  if (quorum > totalSupply / 5)
    minQuorumDivisor = 5;
 }

// Execute result
if (quorum >= minQuorum(p.amount) && p.yea > p.nay && proposalCheck) {
  ...
}
```

**Comment by colm** [comment]
IF `quorum >= minQuorum(p.amount)` that does not mean that `(quorum > totalSupply / 5)` and EVEN if `(quorum > totalSupply / 5)` that ensures that `quorum >= minQuorum(p.amount)` with `minQuorumDivisor = 5` so the proposal will always get executed.

So the quorum will only be reset if the original min quorum is achieved. . Otherwise it will stay low.

This was a really nice bug tho!!! Took me a lot of thinking to find the answer. I look forward to the next one ;-)

**Comment by LefterisJP** [comment]
If the `minQuorum` is at 10% due to the minQuorum divisor and a proposal passes and gets to the execution part of the code which you linked then it will not reset `minQuorumDivisor` since `quorum < totalSupply / 5`. 

It will only reset minQuorumDivisor in the case that `quorum > totalSupply / 5` which means that at least 20% of the quorum would have been reached.

**Comment by LefterisJP** [comment]
If the `minQuorum` is at 10% due to the minQuorum divisor and a proposal passes and gets to the execution part of the code which you linked then it will not reset `minQuorumDivisor` since `quorum < totalSupply / 5`. 

It will only reset minQuorumDivisor in the case that `quorum > totalSupply / 5` which means that at least 20% of the quorum would have been reached.
