### ISSUE TITLE
DAO.exectureProposal() issue

### ISSUE THREAD

**Issue by cougarously** [slockit/DAO#220]
**1) Minor change for clarity. The comment below is misleading because calling `newContract()` does not necessarily require 53%. It's actually from 33% to a maximum of 53%. That's because `minQuorumDivisor` can tend toward 0 if a quorum is not met over a long period of time. Current code has:**
```
====> // require 53% for calling newContract()
if (_transactionData.length >= 4 && _transactionData[0] == 0x68
    && _transactionData[1] == 0x37 && _transactionData[2] == 0xff
    && _transactionData[3] == 0x1e
    && quorum < minQuorum(actualBalance() + rewardToken[address(this)])) {

        proposalCheck = false;
}
```

**2) There seems to be something strange in that a newContract() is not not called but you can get into a situation where the DAO sends proposalDeposits to itself. In addition, when the the minQuorum (between 33%  and 53%) is not met for calling newContract() but we can still have a situation where we reset the divisor and last time quorum was met:** 

```
// require 53% for calling newContract()
if (_transactionData.length >= 4 && _transactionData[0] == 0x68
    && _transactionData[1] == 0x37 && _transactionData[2] == 0xff
    && _transactionData[3] == 0x1e
    && quorum < minQuorum(actualBalance() + rewardToken[address(this)])) {

        proposalCheck = false;

       ===> The newContract will not get executed if we dont reach 53%
       ===> (given a minQuorumDivisor of 5)
}

if (quorum >= minQuorum(p.amount)) {

    ===> Although we haven't reached 53% 
    ===> we may have reached 21% (for example), so we are here 
    ===> where we send ourselves proposalDeposit and spend gas. 
   
   if (!p.creator.send(p.proposalDeposit))
        throw;

    lastTimeMinQuorumMet = now;
    // set the minQuorum to 20% again, in the case it has been reached
    if (quorum > totalSupply / 5)

        ===> We are in this if statement since we reached 21%.
        ===> It seems strange that we have reset our divisor and 
        ===> lastTimeMinQuorum was met although we will not be executing a
        ===> proposal in this thread of execution. ***
	
        minQuorumDivisor = 5;
}
```

**Comment by LefterisJP** [comment]
@cougarously 
Regarding (1) you are correct, but all comments on the code are essentially assuming a `minQuorumDivisor` of 5.


Regarding (2) that's intentional. `newContract()` is a very special function requiring maxQuorum to be reached in order to be executed. You can imagine upgrading the contract is something that we want all the DTH to agree on!

On the other hand, even if the `maxQuorum` is not reached, but we have reached 21% then it is by design that 2 things should happen:

1. The creator of the proposal gets his deposit back. Even if maxQuorum is not reached, we allow him to get his money back if enough people (minQuorum) voted.

2. Since `minQuorum` is reached then the `minQuorumDivisor` is reset to 5 as is the design. I understand that in your scenario it may be a bit confusing since `newContract()` will not actually get called but this is how the contract works.


Thanks for taking the time to read through the code and challenge the way it is written. It's awesome to have people like you around. Does the above answer your question?

**Comment by cougarously** [comment]
Yes it a lot of sense, thanks for the explanation.

> Thanks for taking the time to read through the code and challenge the way it is written.

No problems. Thank you for taking time with the detailed explanation. I'm sure that you guys want to move on to working on the core of your business (USN and other things) and I appreciate all that's put into this effort.
