### ISSUE TITLE
Errors when trying to compile with solc-js

### ISSUE THREAD

**Issue by wcerfgba** [slockit/DAO#223]
I have written the following JS:

```
var fs = require("fs");
var process = require("process");
var solc = require("solc");

var files = { };
for (var i = 2; i < process.argv.length; i++) {
    var file = process.argv[i];
    files[file] = fs.readFileSync(file).toString("utf-8");
}

var compiled = solc.compile({ sources: files });

console.log(compiled);
```

and placed it at the root of the repo as `verify.js`. I have done `npm install solc` to get the dependency. When I run `node verify.js *.sol libs/*.sol`, I get the following errors:

```
{ errors: 
   [ 'PFOffer.sol:245:16: Error: Operator > not compatible with types bool and uint256\n            && votingDeadline > now\n               ^------------------^\n',
     'PFOffer.sol:255:9: Error: Wildcard both at beginning and end of variable declaration list is only allowed if the number of components is equal.\n        var (,,,votingDeadline,,,,,,yea,nay,) = client.proposals(proposalID);\n        ^------------------------------------------------------------------^\n' ] }
```

**Comment by LefterisJP** [comment]
Hey there. PFOffer is quite picky on the solidity requirement.

As [the comment](https://github.com/slockit/DAO/blob/master/PFOffer.sol#L34) on PFOffer.sol specifies you need a quite bleeding edge solidity version to compile it.

It needs to include a specific [bug](https://github.com/ethereum/solidity/issues/598#issuecomment-224015639) [fix](https://github.com/ethereum/solidity/pull/624). To my knowledge there has been no solidity release since this bug was fixed. As soon as there is one we will change the comment in PFOffer to set it as the minimum requirement.

**Comment by wcerfgba** [comment]
Thanks for your help.

Turns out there are two soljson releases with the aforementioned patch, and I have managed to get around this issue with:
```
solc.loadRemoteVersion('latest', function (err, solcSnapshot) {
     if (err) {
        console.log(err);
        process.exit(1);
    }

    solc = solcSnapshot;
});
```
however, now I get:
```{"errors":["Internal compiler error: Compiled contract not found.\n"]}```
which would appear to be emanating from [solidity/compilerContext.cpp:73](https://github.com/ethereum/solidity/blob/30284487f2178c605fd5f414254803d3370341ef/libsolidity/codegen/CompilerContext.cpp#L73).
