### ISSUE TITLE
DIR 3 - The yes bias and disinsentive to vote no

### ISSUE THREAD

**Issue by LefterisJP** [slockit/DAO#251]
### Changelog

13-06-2016: DIR created
### Problem Definition

Voting “no” can actually help a proposal to succeed. This is due to a design flaw in the quorum logic where both "yea" and "nay" contribute towards the quorum requirements of a proposal. Thus there is a strong disinsentive to vote "nay" since a voter may actually end up helping the proposal they want to downvote.
### Proposed Solution

Only the yes votes should count towards the quorum of a proposal. Additionally the `minQuorum` should be reduced to 14.3%. The implementation of the above can be seen in [this](https://github.com/slockit/DAO/pull/245) PR.

**Comment by Srknbyr** [comment]
Voting "no" instead of no voting can help the attacker to reach quorum, that's right. But an attacker with huge voting power can easily reach quorum by voting "yea".
If you guys can make a "Dynamic voting power" solution, that can help the TheDAO ecosystem.
For example;
when a proposal is revealed, a survey to DTH about that proposal can start. The survey will be on for at least 1 week. If more than %50 of DHT** says that we read the proposal and understand the purpose of proposal then 2 weeks of voting process can start. 
In the first week 1 DAO vote = 1, 
day 8, 1 DAO vote = 0.9,
day 9, 1 DAO vote = 0.8,
day 10, 1 DAO vote = 0.7,
day 11, 1 DAO vote = 0.6,
day 12, 1 DAO vote = 0.5,
day 13, 1 DAO vote = 0.4,
day 14, 1 DAO vote = 0.3..
-----------------------------------
Then if there is an attacker an if that person waits for the last day then his voting power decreases dramatically.
-----------------------------------
** For the survey i mean DTH by the number of accounts instead of DAO tokens.

**Comment by remyroy** [comment]
Why 14.3%? Where is that number coming from? Why not a different number?

**Comment by GriffGreen** [comment]
The goal was to keep it true to the previous 20% and guess how many yes votes that would have been.
We thought maybe 15% yeas and 5% nays.

7 was a round number and considering that there was a proposal that reached over 10% quorum, 14.3% seemed fair.

**Comment by A2be** [comment]
@Srknbyr : re this comment you made: "an attacker with huge voting power can easily reach quorum by voting "yea"."

Are you assuming in your comment that the proposal itself was an "attack" and that the token holders either don't recognize it as an attack, or fail to vote "no" in sufficient numbers to cancel the "huge voting power" malicious actor?

If not, I'm not getting your point about "yea" votes and an attack.

**Comment by Srknbyr** [comment]
@A2be : Token holders can realise that it is an attack and they can vote no, but what if an attacker with huge voting power waits for the proposal's last minutes and vote "Yea" ?

This is why i thought a dramatically decrease on voting power day after day can help avoiding last second attacks..

**Comment by GriffGreen** [comment]
@Srknbyr Considering that there is no disincentive to vote no and because the `preSupportTime = 2 days` in [DIR 3](https://github.com/slockit/DAO/issues/252), a proposal has to have majority support 2 days before the end of the debating period and if it does, and its a horrible proposal, there is nothing stopping people from emphatically voting no and raising the alarm, if there is a strong yes vote to over come this, well that is called voting... it's hardly an attack.  

And because the 'splitGracePeriod = 3 days' there are lots of ways to get out of The DAO (splitting, withdrawing, and trading your tokens) that people can use if they strongly disagree with the proposal. 

#keepingItSimple4DAO1.1
