### ISSUE TITLE
p.proposalDeposit check should be removed from splitDAO

### ISSUE THREAD

**Issue by colm** [slockit/DAO#58]
If the proposal Deposit is included in the DAO then a malicious attacker could set the limit prohibitively high to prevent splits. 

```
if (address(p.splitData[0].newDAO) == 0)
  throw;
// p.proposalDeposit should be zero here
if (this.balance < p.proposalDeposit)
  throw;
p.splitData[0].splitBalance = this.balance - p.proposalDeposit;
p.splitData[0].rewardToken = rewardToken[address(this)];
p.splitData[0].totalSupply = totalSupply;
p.proposalPassed = true;
```

**Comment by colm** [comment]
https://github.com/slockit/DAO/pull/56 fixes this issue

**Comment by LefterisJP** [comment]
Hello. Two things:

Do not mix PRs. You already had PR #56 which proposes to remove the excess checks in `SampleOffer.sol`. That's one Pull Request. For anything else make another one.

As for your issue here I am a bit confused. What do you see as a problem? The lines you removed in the PR:

```diff
-            // p.proposalDeposit should be zero here
-            if (this.balance < p.proposalDeposit)
-                throw;
```

simply only check if the proposal deposit is zero there, since a DAO split is a special kind of proposal where the proposal deposit should be zero.

**Comment by colm** [comment]
shit i'll fix that. 

ah okay i thought p.proposalDeposit was globally set by the DAO vote. 

But anyway there is no need for it here. Who cares if someone sends more than zero? If some one does then its okay. Checking is a waste of gas. What you think?

**Comment by LefterisJP** [comment]
It is just a sanity check and happens only once. Happens only at the very first call of the `splitDAO()` when the new DAO address is created. 

We do care because we want to protect the user. As per the white paper, DAO split proposals should require no deposit.

But it may indeed be a redundant check. Any new proposal to split the DAO will go through the `newProposal()` function. There with `_newServiceProvider` being `true` at [this line](https://github.com/slockit/DAO/blob/master/DAO.sol#L360) we check if no proposal deposit has been given. Then at `splitDAO()` at [this line](https://github.com/slockit/DAO/blob/master/DAO.sol#L524) we also check that it's indeed a split proposal that is being executed so we are on the same execution path.

So the check may be indeed redundant. What do you think @CJentzsch?

**Comment by CJentzsch** [comment]
The proposal deposit for a new service provider is `>=0` . So it can be zero (to prevent the attack that a 51% guy sets it too high), but one can have a higher number to be listed on top of the list of proposals. We will list them after proposal deposit in the GUI

**Comment by colm** [comment]
But there is no need to check this here. The proposal deposit can be either zero or more, it cannot be negative. Checking it here is a waste of gas and extra complexity. This if loop will always return true.
