### ISSUE TITLE
Mistake in checking of `closingTime`

### ISSUE THREAD

**Issue by colm** [slockit/DAO#77]
`if (now < closingTime + 40 days)` [here](https://github.com/slockit/DAO/blob/master/DAO.sol#L356)
should be ` if (now < closingTime)` There are no errors introduced by this because it is double checked in `buyTokenProxy`

**Comment by LefterisJP** [comment]
This is not a mistake. It's a grace period calculated in there by design.

You are looking at the fallback function of the DAO. If you just send a transaction to the DAO with a value this is what is called. When called during the sale you will receive tokens, 40 days after the sale you will attempt and fail to buy tokens (but still get your money back). After that grace period you are essentially making a donation to the DAO.

Quoting the White Paper:

>In order to protect users, this function will send the ether received
>after the end of the sale back to the sender for a time period
> of 40 days. After which this function is repurposed
> to receive ether as simple deposit to the DAO using the
> function receiveEther.
