### ISSUE TITLE
 `executeProposal` takes `_transactionData` as input not `p._transactionData`

### ISSUE THREAD

**Issue by colm** [slockit/DAO#80]
Because `executeProposal` takes `_transactionData` as a function input and not from `p._transactionData` [here](https://github.com/slockit/DAO/blob/master/DAO.sol#L488) and [here](https://github.com/slockit/DAO/blob/master/DAO.sol#L509)

There is no problem here. However because [sha3](http://solidity.readthedocs.org/en/latest/units-and-global-variables.html#mathematical-and-cryptographic-functions) concatenates without padding an attacker can inject a malicious `_transactionData` into the `executeProposal` function along as it is concentrated with `p.recipient` and `p.amount` the check will catch it. But I would be a little more comfortable if we used `p._transactionData` here.

Is there a reason we take `_transactionData` as input?

**Comment by LefterisJP** [comment]
Is this issue just for a question? Because as you pointed out [this check](https://github.com/slockit/DAO/blob/master/DAO.sol#L488) will catch any malicious `_transactionData` injection.

But yes I am not sure why we `_transactionData` is given as an argument here and not saved inside the proposal itself as `p.transactionData`. @CJentzsch can help us with that.

**Comment by colm** [comment]
Just a question. That check catches it. I would just rather it it was `p.transactionData`

**Comment by CJentzsch** [comment]
There is no `p.transactionData`. I want to avoid typos, so when executing the one doing it makes sure he does so on the right proposal. The voters can always use `checkProposalCode` to check whether they vote on the right proposal. Does this answer your question @colm ?

**Comment by LefterisJP** [comment]
@CJentzsch But isn't it better to have it as `p.transactionData`? And then the only thing the user who executes the proposal has to do is check the proposalD is correct? 

This way we can remove:
1) The `bytes _transactionData` argument from `executeProposal()`
2) The `p.proposalHash` member will no longer be needed
3) The check `|| p.proposalHash != sha3(p.recipient, p.amount, _transactionData)) {`

**Comment by CJentzsch** [comment]
Sure, but we have this mechanism exactly because of the reason to avoid accidently executing the wrong proposal.this was build from Christian and Avsa in the original DAO contract.

**Comment by LefterisJP** [comment]
So it's a choice between having an extra safeguard (apart from checking that you are executing the correct proposal ID) and reducing the complexity of the code by removing the 3 bullet points I showcased [above](https://github.com/slockit/DAO/issues/80#issuecomment-208270241).

I don't see the reason for this safeguard when we can actually simplify the code instead.
@chriseth I would really appreciate your thoughts on this.

**Comment by chriseth** [comment]
The original code was a bit over-engineered and had some unnecessary optimizations. Preventing accidental proposal executions is a good point, but it would probably be more an issue of the UI, wouldn't it?
The fact that sha3 concatenates without padding is not an issue, because it does not encode the data according to its value but rather according to its type, so you could say that it does add some kind of padding, but only the native padding of the type.

**Comment by colm** [comment]
hmm interesting. 

The case for preventing accidental executions is weak. As a proposal must be passed before this becomes an issue. Then this requires 

1. Every token holder agrees not to execute a function that has been approved until the agreed upon moment. 
2. The proposal creator has to forgo the deposit they placed when the proposal was created.
3. Then all the people who voted for or against the proposal cannot vote or split until the proposal gets executed. 

Having an extra protection against execution by accident seems to be over kill.

**Comment by CJentzsch** [comment]
I decided to leave it as is for two reasons:
 
1.) it add a tiny bit more safety (I agree, really not much, almost nothing)

2.) more importantly, it make the size of a proposal constant. If I would add `bytes transactionData` then a proposal could be very long, since it has no finite size. Although this shouldn't lead to a problem there is tiny risk involved with it

3.)  it saves gas since one only stores 32 bytes (hash) instead of the real transaction data, which is usually much longer.

Both ways would be ok, but for the above reasons, and since I don't want to change to much code again, I leave it as is.

**Comment by LefterisJP** [comment]
@CJentzsch Regarding (2):

Even now proposals are not constant size. They got `string description;` in them which, just like `bytes` is variable sized. They also got mappings and a SplitData array.
