### ISSUE TITLE
`withdrawRewardFor` can be called for any address

### ISSUE THREAD

**Issue by colm** [slockit/DAO#91]
[Calling](https://github.com/slockit/DAO/blob/master/DAO.sol#L724) `transferFromWithoutReward` allows an attacker to call the `withdrawRewardFor` which is an internal function and send the rewards of any user to that users account. 

This can be scripted away to make a large % of every users rewards be charged as fees for these micro withdrawals.

**Comment by LefterisJP** [comment]
I believe this is not a problem because the attacker must have been given [approval](https://github.com/slockit/DAO/blob/master/Token.sol#L122) by the guy whose address he is trying to transferFrom.

 If he does not have the approval then he is not in the [allowed list](https://github.com/slockit/DAO/blob/master/Token.sol#L109). Thus TokenSale.sol's [`transferFrom()`](https://github.com/slockit/DAO/blob/master/Token.sol#L118) will return an error which will lead the DAO.sol's overriden `transferFrom()` to [throw](https://github.com/slockit/DAO/blob/master/DAO.sol#L719). 

Therefore the transaction would get completely reverted.

**Comment by colm** [comment]
oh thats pretty cool.

**Comment by LefterisJP** [comment]
@colm Sorry for the links being off, things got merged into master in the meantime.

note to self: When making links in github link to particular commits.

**Comment by colm** [comment]
no problem. I will do that same with my links ;-)
